name: Test suite
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.15"

      - name: Test
        run: make test build
